version: "3"

services:

  backend:
    build:
      context: '.'
      dockerfile: 'docker/Dockerfile'
    command: 'daphne -b 0.0.0.0 -p 8000 pytality_server.asgi:application'
    restart: 'always'
    depends_on:
      - db
      - redis
    volumes:
      - '.:/app/'
    ports:
      - '8000'
    env_file:
      - '.env'
      
  db:
    image: 'postgres:latest'
    env_file:
      - '.env'
    restart: 'always'
    volumes:
      - 'db-data:/var/lib/postgresql/data'
      
  redis:
    image: 'redis:latest'
    restart: 'always'
    ports:
      - '6379'
    volumes:
      - 'redis-data:/data'

volumes:
  db-data:
  redis-data: