# Generated by Django 2.1 on 2018-08-18 13:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='wrong_code',
            new_name='incorrect_code',
        ),
    ]
