# Generated by Django 2.1 on 2018-08-18 13:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_auto_20180818_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='input_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='snippet',
            name='used_in_current_rotation',
            field=models.BooleanField(default=False),
        ),
    ]
